### numerical python

In [1]:
import numpy as np

In [2]:
arr = np.array([12,23,45,56,32])

In [3]:
arr

array([12, 23, 45, 56, 32])

In [4]:
print(arr)

[12 23 45 56 32]


In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.dtype 

dtype('int32')

In [7]:
arr = np.array([12,23,45,56,32,66.4])
arr.dtype

dtype('float64')

In [9]:
arr = np.array([12,23,45,56,32,'aryan'])
print(arr)
arr.dtype

['12' '23' '45' '56' '32' 'aryan']


dtype('<U11')

In [11]:
%%timeit
arr = np.array([12,23,45,56,32,66.4,'pune'])

2.42 µs ± 18.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [12]:
print(arr[3])

56


In [14]:
arr.shape

(6,)

In [17]:
arr = np.array([12,23,45,56,32])
arr * 2

array([ 24,  46,  90, 112,  64])

In [18]:
arr

array([12, 23, 45, 56, 32])

In [22]:
 np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
np.arange(2,12,1.5)

array([ 2. ,  3.5,  5. ,  6.5,  8. ,  9.5, 11. ])

In [24]:
range(2,12,1.5)

TypeError: 'float' object cannot be interpreted as an integer

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
#2d array

In [30]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [31]:
print(arr1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [32]:
arr1.shape # shape

(4, 3)

In [33]:
arr1.ndim # checks dim

2

In [35]:
arr1.flatten() # converts into 1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
arr1.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
arr1.size

12

In [45]:
arr1.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [46]:
arr1.reshape(6,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [49]:
arr1.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [50]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [51]:
arr1[0:3, 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [52]:
arr

array([12, 23, 45, 56, 32])

In [55]:
arr.mean()

33.6

In [56]:
arr.min()

12

In [54]:
arr2 = np.array([11,22,33,22,33,55])
np.unique(arr2)

array([11, 22, 33, 55])

In [58]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [59]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
np.linalg.det(arr1)

6.66133814775094e-16

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [62]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])